name: Build

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install packages
      shell: pwsh
      run: |
        npm i -g @vercel/ncc
        npm install

    - name: Build
      shell: pwsh
      run: ./.github/.scripts/build.ps1
